#!/bin/bash
# pos-arg-demo : positional parameter/argument demo with for/while loop
# demonstrate shell function with parameter too

progname=$(basename $0)
echo "$progname with $# parameters. "
# echo "Program = $(basename $0)
# \$0 = "$0"
# \$1 = $1
# \$2 = $2
# \$3 = $3
# \$4 = $4
# \$5 = $5"
count=1
for i; do
	echo "\$$count=$i"
	((++count))
done

print_out_parameter () { 
while [ $# -gt 0 ]; do
	echo "$1"
	shift
done
}

echo  "\$*: "
print_out_parameter $*
echo '"$*" '
print_out_parameter "$*" 
echo  "\$@"
print_out_parameter $@
echo '"$@" '
print_out_parameter "$@"

show_func_name () {
	echo "$FUNCNAME"
	return
}

show_func_name
